site_name: Greenv2 MVP
site_url: https://www.greenv2.com
site_description: Project documentation about Greenv2 MVP.
site_author: Greenv2 Team

repo_url: https://github.ibm.com/frederic-dutheil/Greenv2

nav:
    - Home: index.md
    - User Guide :
        - Overview: DEMO.md
        - Initial Setup: INITIAL-SETUP.md
        - Deployment: DEPLOY-CONTAINERS.md
        - Certificates: CERTIFICATE-SETUP.md
        - 'Cloud Object Storage': 'Drupal-Cloud-Object-Storage.md' 
    - Lessons Learned: lessons.md
    - App Modernization Map: appmodernizationmap.md
    - About: about.md

extra_css:
    - css/extra.css

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

#theme: readthedocs