---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prd
spec:
  loadBalancerIP: xxx.xx.xxx.xxx # Change to public from kubectl get cm ibm-cloud-provider-vlan-ip-config -n kube-system -o yaml
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-prd
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-prd
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-prd
        tier: frontend
        track: stable
    spec:
      containers:
        - env:
            - name: BUILD_TIME
              value: '2706'
            - name: ENV
              value: "prod"
          image: "uk.icr.io/greenv2-ns/code-nginx:latest"
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - "-s"
                  - quit
          name: nginx-prd
          imagePullPolicy: Always # Set to IfNotPresent to improve performance at the expense of caching.
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /var/www/drupal/web/sites/default/files
              name: sites-local-storage
      imagePullSecrets:
        - name: default-uk-icr-io
      volumes:
        - name: sites-local-storage
          persistentVolumeClaim:
            claimName: sites-prd-lv-claim
