apiVersion: v1
kind: Service
metadata:
  name: nginx-stg
spec:
  loadBalancerIP: xxxx.xx.xx.xxx  # Change to public from kubectl get cm ibm-cloud-provider-vlan-ip-config -n kube-system -o yaml
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-stg
    tier: frontend
  type: LoadBalancer
