apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
   ingress.bluemix.net/redirect-to-https: "True"
spec:
  tls:
  - hosts:
    - xxx.xxxxx.com
    secretName: tls-secret
  rules:
  - host: xxxxx.xxxxx.xxxxxx.cloud #find by running ibmcloud cs cluster-get <cluster name>
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-stg
          servicePort: 80
  - host: xxxx.xxxx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-stg
          servicePort: 80
